@startuml nbodysystem

Class ISystem {
    +addBody(Body)
    +removeBody(Body)
    +getBodies()

    + virtual step() = 0
}

class System { 
}

class Body {
    +update(acceleration, dt)
    -position
    -mass
    -volume
    -color
}

class ISystemPublisher {
    +virtual publish(ISystem) = 0
}

class gRPCPublisher {

}

class consolePublisher {}

class NullPublisher {}

ISystem <|-- System
ISystem "1" -o "n" Body 

ISystemPublisher <|-- gRPCPublisher
ISystemPublisher <|-- consolePublisher
ISystemPublisher <|-- NullPublisher
@enduml